name: Demo Docker Hub Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Connexion Ã  Docker Hub (Utilise vos secrets GitHub)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 2. Configuration du builder moderne
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Construction et Push vers Docker Hub
      - name: Build and push PHP image
        uses: docker/build-push-action@v5
        with:
          context: ./php
          push: true
          # FORMAT CORRECT : pseudo/nom-image:version (Tout en minuscules)
          tags: mareme2930/php-apache-crud:1

      # 4. Test final du lancement des services
      - name: Test Docker Compose launch
        run: docker-compose up -d --build
# Trigger commit 2026
