name: Demo Docker Hub Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 2. Configuration du builder
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Construction et Push
      - name: Build and push PHP image
        uses: docker/build-push-action@v5
        with:
          context: ./php
          push: true
          # On force le passage en minuscules pour éviter l'erreur de tag Docker
          tags: mareme20/php/php-apache-crud:1

      # 4. Test du lancement des services
      - name: Test Docker Compose launch
        run: docker-compose up -d --build
